learningUsers/basic/urls.py
from django.urls import path,include
from basic import views

app_name='basic'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('user_login',views.user_login,name='user_login')

]

learningUsers/learningUsers/urls.py
from django.contrib import admin
from django.urls import path,include
from basic import views

urlpatterns = [
    path('',views.index,name='index'),
    path('basic/',include('basic.urls')),
    path('admin/', admin.site.urls),
    path('logout/',views.user_logout,name='log_out'),
    path('special/',views.special,name='special'),
]

learningUsers/basic/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfile(models.Model):

    user=models.OneToOneField(User,on_delete=models.DO_NOTHING)

    #additional
    portFolio=models.URLField(blank=True)
    profilePic=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

learningUsers/basic/forms.py
from django import forms
from django.contrib.auth.models import User
from basic.models import UserProfile

class UserForm(forms.ModelForm):
    password =forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields =('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model=UserProfile
        fields=('portFolio','profilePic')

learningUsers/basic/views.py
from django.shortcuts import render
from basic.forms import UserForm,UserProfileForm
# Create your views here.
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
def index(request):
    return render(request,'basic/index.html')

@login_required
def special(request):
    return HttpResponse('you are logged in nice!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



def register(request):
    registered=False

    if request.method == "POST":
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user =user_form.save()
            user.set_password(user.password)
            user.save()

            profile =profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered=True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserProfileForm()
    return render(request,'basic/registration.html',
        {'user_form':user_form,
        'profile_form':profile_form,
        'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password =request.POST.get('password')

        user=authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account Not Active!")
        else:
            print("Login Failure")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("Invalid Login Details!")
    else:
        return render(request,'basic/login.html')

learningUsers/templates/basic/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class='navbar navbar-default navbar-static-top'>
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{% url 'index' %}">Home</a> </li>
          <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>
          <li> <a class="navbar-link" href="{% url 'basic:register' %}">Register</a> </li>

            {% if user.is_authenticated %}
              <li> <a class='navbar-link' href="{% url 'log_out' %}"> logout</a></li>
              <li> <a class='navbar-link' href="{% url 'special' %}"> special</a></li>
            {% else %}
              <li> <a class='navbar-link' href="{% url 'basic:user_login' %}">login</a> </li>
            {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learningUsers/templates/basic/index.html
{% extends "basic/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django level five</h1><br>
    <h2>User Authentication</h2>
  </div>
{% endblock %}

learningUsers/templates/basic/login.html
{% extends 'basic/base.html' %}

{% block body_block %}

  <div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'basic:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="enter user name">
        <br><br>
        <label for="password">Password</label>
        <input type="password" name="password" value="">
        <br><br>
        <input type="submit" name="" value="login">
    </form>
  </div>

{% endblock %}

learningUsers/templates/basic/registration.html
{% extends "basic/base.html" %}
{% load static %}


{% block body_block %}

  <div class="jumbotron">
    {% if registered %}
      <h1>Thank You for registering!</h1>

    {% else %}
      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>
{% endblock %}